# Generated by Django 3.2.6 on 2021-08-04 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sign', models.CharField(max_length=10)),
                ('unit_type', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=5)),
                ('event_id', models.CharField(max_length=10, null=True)),
                ('event_type', models.CharField(max_length=10, null=True)),
                ('event_sub_type', models.CharField(max_length=10, null=True)),
                ('location', models.CharField(max_length=30, null=True)),
                ('unit_phone_number', models.CharField(max_length=10, null=True)),
                ('employee_one', models.CharField(max_length=30, null=True)),
                ('employee_two', models.CharField(max_length=30, null=True)),
                ('last_status_change', models.DateTimeField(auto_now=True)),
                ('out_of_service_code', models.CharField(blank=True, max_length=10, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.station')),
            ],
        ),
        migrations.CreateModel(
            name='Broadcast_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_time', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.station')),
            ],
        ),
    ]
